# Generated by Django 3.0.7 on 2020-06-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonres_only', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonres_model',
            old_name='introduction',
            new_name='coment',
        ),
    ]
